"""Public shape-augmentation API.

The implementation lives in :mod:`kore.tasks.shape_policy` so task source
generators and runtime evaluation consume the same declarative policy engine.
"""

from kore.tasks.shape_policy import (
    BOUNDARY_REGIMES,
    MANIFEST_SCHEMA_VERSION,
    POLICY_SCHEMA_VERSION,
    AtomicShapeTransform,
    FrozenShapeSplit,
    RegistryShapeAudit,
    ShapeAugmentationPolicy,
    ShapeConstraint,
    TaskShapeAudit,
    audit_registry_augmentation,
    audit_registry_shapes,
    audit_task_shapes,
    augment_shapes,
    augmentation_policy,
    augmentation_policy_for_task,
    boundary_regime,
    constraint_errors,
    freeze_shape_split,
    generate_hidden_shapes,
    generated_shape_error,
    policy_digest,
    policy_metadata_for_shapes,
    shape_key,
    shape_policy_yaml_lines,
    validate_frozen_split,
)

__all__ = [
    "BOUNDARY_REGIMES",
    "MANIFEST_SCHEMA_VERSION",
    "POLICY_SCHEMA_VERSION",
    "AtomicShapeTransform",
    "FrozenShapeSplit",
    "RegistryShapeAudit",
    "ShapeAugmentationPolicy",
    "ShapeConstraint",
    "TaskShapeAudit",
    "audit_registry_augmentation",
    "audit_registry_shapes",
    "audit_task_shapes",
    "augment_shapes",
    "augmentation_policy",
    "augmentation_policy_for_task",
    "boundary_regime",
    "constraint_errors",
    "freeze_shape_split",
    "generate_hidden_shapes",
    "generated_shape_error",
    "policy_digest",
    "policy_metadata_for_shapes",
    "shape_key",
    "shape_policy_yaml_lines",
    "validate_frozen_split",
]
