"""SOTA code-corpus quality filtering for the Stage-0 mid-train corpus builder.

The mid-train (continued-pretraining) corpus ingests raw source files from
GPU-kernel repos (Triton ``.py``, HIP/CUDA/C++ ``.cu``/``.cpp``/``.h``, ROCm
``.md`` docs) + HF kernel datasets as ``(path, text)`` tuples. The historical
gate was only ``len(text) > 20 and "__pycache__" not in text`` — which lets in
minified/generated blobs, protobuf stubs, vendored dependencies, license-only
docs, and trivial stubs. Training on that junk wastes capacity and dilutes the
high-signal domain code we actually want the policy to learn.

This module is the real quality gate. It follows the public code-corpus recipe
established by The-Stack-v2 / StarCoder2 (BigCode) and the RedPajama/Gopher
document-quality heuristics, specialized for a *kernel* corpus:

  * **Line-length gates** drop minified / machine-generated one-liners
    (``max line > 1000`` or ``mean line > 100``).
  * **Alphanumeric-fraction gate** drops mostly-punctuation / binary-ish files.
  * **Triviality gate** drops empty stubs (too few real code lines / chars).
  * **Autogenerated-marker gate** drops files banners like ``@generated`` /
    ``DO NOT EDIT`` / whole-file ``clang-format off`` / lockfiles.
  * **Path gate** drops vendored / generated / dependency trees
    (``third_party/``, ``node_modules/``, ``*_pb2.py`` …).
  * **Self-repetition gate** drops boilerplate / unrolled dumps.

Deliberately ABSENT: a minimum-comment-ratio filter. Generic web-code filters
often require a comment ratio, but *real* dense GPU kernels (flash-attention
Triton, Composable-Kernel fp8 GEMM) are intentionally comment-sparse and use
long-ish lines — a comment-ratio gate would throw away exactly the code we most
want. The repetition gate is likewise refined: a naive "> 50% of lines are exact
duplicates" rule drops legitimate multi-kernel files (e.g. Tri Dao's
``flash_attn_triton.py`` repeats short argument / brace lines across its
fwd/bwd kernels and measures 0.62 duplicate-line fraction). We therefore require
BOTH a high duplicate-*line* fraction AND a high duplicate-*character* fraction:
real kernels repeat many *short* lines (little character mass) whereas genuine
boilerplate/dumps repeat their *bulk* (see ``MAX_DUP_LINE_FRACTION`` /
``MAX_DUP_CHAR_FRACTION``).

Every predicate has a ``*_reason`` variant returning ``None`` (keep) or a short,
stable reason string (drop), so :func:`quality_filter` can report actionable
per-reason drop counts. Pure stdlib, deterministic, fast, and free of import
side effects, so ``from kore.data.corpus_quality import quality_filter`` is cheap.

Public API
----------
    code_quality_ok(text, path=None)   -> bool
    code_quality_reason(text, path=None) -> Optional[str]
    doc_quality_ok(text, path=None)    -> bool
    doc_quality_reason(text, path=None)  -> Optional[str]
    quality_filter(files, is_doc=False)  -> (kept, stats)

All thresholds are module constants so they can be tuned without touching logic.
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

# --------------------------------------------------------------------------- #
# Tunable thresholds (module constants).
# --------------------------------------------------------------------------- #
#: Drop if the single longest line exceeds this many characters (minified).
MAX_LINE_LENGTH = 1000
#: Drop if the mean non-empty line length exceeds this (minified / generated).
MAX_MEAN_LINE_LENGTH = 100.0
#: Drop if the alphanumeric fraction of non-whitespace chars is below this.
MIN_ALNUM_FRACTION = 0.25
#: Drop if fewer than this many non-empty, non-comment code lines remain.
MIN_CODE_LINES = 3
#: Drop if fewer than this many characters of real (comment-stripped) code.
MIN_CODE_CHARS = 50
#: Self-repetition: drop only when BOTH fractions exceed their threshold.
MAX_DUP_LINE_FRACTION = 0.50
MAX_DUP_CHAR_FRACTION = 0.50
#: Only apply the repetition gate to files with at least this many non-empty
#: lines (tiny files are governed by the triviality gate instead).
REPETITION_MIN_LINES = 8
#: Only scan this many leading characters for autogenerated banners.
GENERATED_HEAD_CHARS = 2048

#: Docs: minimum raw stripped length to be worth keeping.
MIN_DOC_CHARS = 200
#: Docs: minimum alphabetic prose characters after stripping markup/links/code.
MIN_DOC_PROSE_CHARS = 120
#: Docs: minimum prose word count (guards against nav/badge-only stubs).
MIN_DOC_WORDS = 20

# --------------------------------------------------------------------------- #
# Marker / path vocabularies.
# --------------------------------------------------------------------------- #
#: Autogenerated banners; matched case-insensitively near the top of a file.
_GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "autogenerated",
    "auto-generated",
    "code generated by",
    "this file was automatically generated",
    "this file is automatically generated",
    "generated by the protocol buffer compiler",
)

#: Path parts (case-insensitive) that mark vendored / generated / dep trees.
_VENDOR_DIR_PARTS = frozenset({
    "third_party", "3rdparty", "thirdparty", "vendor", "vendored", "external",
    "node_modules", "dist", "build", ".git", "__pycache__", "site-packages",
    "googletest", "gtest", "pybind11",
})

#: Filename suffixes that mark generated sources (protobuf, …).
_GENERATED_SUFFIXES = ("_pb2.py", ".pb.h", ".pb.cc", ".pb.go")

#: Dependency lockfiles (matched by exact lowercased filename).
_LOCKFILE_NAMES = frozenset({
    "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml",
    "packages.lock.json", "cargo.lock", "poetry.lock", "pipfile.lock",
    "pdm.lock", "uv.lock", "composer.lock", "gemfile.lock", "go.sum",
    "flake.lock", "bun.lockb",
})

#: License markers that gate the doc "license-only" check (case-insensitive).
_LICENSE_MARKERS = (
    "spdx-license-identifier",
    "permission is hereby granted",
    "redistribution and use in source",
    "licensed under the apache license",
    "gnu general public license",
    "mozilla public license",
    "the software is provided",
    "without warranty of any kind",
    "copyright (c)",
    "all rights reserved",
)

#: Tokens marking an individual line as license/copyright boilerplate. Used only
#: inside the (marker-gated) license-only branch to strip license text and see
#: whether any real prose remains.
_LICENSE_LINE_TOKENS = (
    "license", "copyright", "spdx", "permission", "warrant", "redistribut",
    "sublicense", "the software", "software", "merchantability",
    "noninfringement", "liable", "damages", "free of charge",
    "documentation files", "rights reserved", "as is", "provided",
)

#: Extensions whose line comment is ``#`` (and no ``/* */`` block comments).
_HASH_COMMENT_EXTS = frozenset({
    ".py", ".pyi", ".pyx", ".pxd", ".sh", ".bash", ".zsh", ".rb", ".pl", ".r",
    ".jl", ".yaml", ".yml", ".toml", ".cfg", ".ini", ".mk", ".cmake",
})
#: Extensions whose comments are ``//`` line + ``/* */`` block (C-family etc.).
_SLASH_COMMENT_EXTS = frozenset({
    ".c", ".cc", ".cpp", ".cxx", ".c++", ".h", ".hh", ".hpp", ".hxx", ".cu",
    ".cuh", ".hip", ".cl", ".js", ".jsx", ".ts", ".tsx", ".java", ".go",
    ".rs", ".metal", ".m", ".mm",
})

#: Stable vocabulary of drop reasons (useful for tests / dashboards).
CODE_DROP_REASONS = (
    "lockfile", "vendored_path", "generated_path", "generated_marker",
    "long_lines", "low_alnum", "too_trivial", "repetitive",
)
DOC_DROP_REASONS = ("doc_too_short", "license_only", "low_prose")


# --------------------------------------------------------------------------- #
# Small helpers.
# --------------------------------------------------------------------------- #
def _as_path(path) -> Optional[Path]:
    if path is None:
        return None
    return path if isinstance(path, Path) else Path(str(path))


def _comment_style(path) -> Optional[str]:
    """Return ``"hash"``, ``"slash"``, or ``None`` (unknown) for a path."""
    p = _as_path(path)
    if p is None:
        return None
    suffix = p.suffix.lower()
    if suffix in _HASH_COMMENT_EXTS:
        return "hash"
    if suffix in _SLASH_COMMENT_EXTS:
        return "slash"
    return None


def _code_lines(text: str, path=None) -> List[str]:
    """Non-empty, non-comment code lines (stripped), best-effort per language.

    Comment handling is language-aware when ``path`` is known so C-family
    ``#include`` directives are kept as code (only ``//`` / ``/* */`` are
    stripped) while Python ``#`` comments are stripped. With an unknown path we
    conservatively strip both styles — this can only *under*-count code, i.e.
    err toward flagging a file as trivial, which never affects real dense
    kernels (they are far above the triviality thresholds).
    """
    style = _comment_style(path)
    s = text
    if style in ("slash", None):
        s = re.sub(r"/\*.*?\*/", "", s, flags=re.DOTALL)  # block comments
    out: List[str] = []
    for line in s.splitlines():
        if style == "hash":
            line = re.sub(r"#.*$", "", line)
        elif style == "slash":
            line = re.sub(r"//.*$", "", line)
        else:  # unknown -> strip both styles (best effort)
            line = re.sub(r"#.*$", "", line)
            line = re.sub(r"//.*$", "", line)
        stripped = line.strip()
        if stripped:
            out.append(stripped)
    return out


def _has_generated_name(name: str) -> bool:
    """True if a (lowercased) filename looks generated (protobuf / ``.generated.``)."""
    if ".generated." in name:
        return True
    return name.endswith(_GENERATED_SUFFIXES)


# --------------------------------------------------------------------------- #
# Code quality
# --------------------------------------------------------------------------- #
def code_quality_reason(text: str, path=None) -> Optional[str]:
    """Return ``None`` to KEEP a code file, else a short reason string to DROP.

    Checks (in order; the first failure is the reported reason):
      1. ``lockfile`` / ``vendored_path`` / ``generated_path`` — path signals.
      2. ``generated_marker`` — autogenerated banner near the top of the file,
         or a whole-file ``clang-format off`` (no matching ``clang-format on``).
      3. ``long_lines`` — max line > ``MAX_LINE_LENGTH`` or mean non-empty line
         length > ``MAX_MEAN_LINE_LENGTH`` (minified / generated).
      4. ``low_alnum`` — alphanumeric fraction of non-whitespace chars <
         ``MIN_ALNUM_FRACTION`` (mostly punctuation / binary-ish).
      5. ``too_trivial`` — fewer than ``MIN_CODE_LINES`` non-empty non-comment
         lines, or fewer than ``MIN_CODE_CHARS`` characters of real code.
      6. ``repetitive`` — both the duplicate-line fraction and the
         duplicate-character fraction exceed their thresholds.
    """
    # 1. Path-based signals (cheap, decisive) ------------------------------- #
    p = _as_path(path)
    if p is not None:
        name = p.name.lower()
        if name in _LOCKFILE_NAMES:
            return "lockfile"
        if {part.lower() for part in p.parts} & _VENDOR_DIR_PARTS:
            return "vendored_path"
        if _has_generated_name(name):
            return "generated_path"

    if not text or not text.strip():
        return "too_trivial"

    # 2. Autogenerated banners --------------------------------------------- #
    head = text[:GENERATED_HEAD_CHARS].lower()
    if any(marker in head for marker in _GENERATED_MARKERS):
        return "generated_marker"
    low = text.lower()
    # Whole-file clang-format disable (a generated-table signal). A *local*
    # ``off``/``on`` block — common in hand-written CK/HIP code — is fine.
    if "clang-format off" in low and "clang-format on" not in low:
        return "generated_marker"

    # 3. Line-length (minified / generated) -------------------------------- #
    lines = text.splitlines()
    nonempty = [ln for ln in lines if ln.strip()]
    max_line = max((len(ln) for ln in lines), default=0)
    mean_line = (sum(len(ln) for ln in nonempty) / len(nonempty)) if nonempty else 0.0
    if max_line > MAX_LINE_LENGTH or mean_line > MAX_MEAN_LINE_LENGTH:
        return "long_lines"

    # 4. Alphanumeric fraction (over non-whitespace) ----------------------- #
    non_ws = [c for c in text if not c.isspace()]
    if non_ws:
        alnum = sum(1 for c in non_ws if c.isalnum())
        if alnum / len(non_ws) < MIN_ALNUM_FRACTION:
            return "low_alnum"

    # 5. Triviality (real code volume) ------------------------------------- #
    code_lines = _code_lines(text, path)
    real_chars = sum(len(ln) for ln in code_lines)
    if len(code_lines) < MIN_CODE_LINES or real_chars < MIN_CODE_CHARS:
        return "too_trivial"

    # 6. Self-repetition (line AND character weighted) --------------------- #
    if len(nonempty) >= REPETITION_MIN_LINES:
        stripped = [ln.strip() for ln in nonempty]
        counts = Counter(stripped)
        dup_values = {ln for ln, c in counts.items() if c >= 2}
        if dup_values:
            dup_lines = sum(c for ln, c in counts.items() if c >= 2)
            line_frac = dup_lines / len(stripped)
            total_chars = sum(len(ln) for ln in stripped)
            dup_chars = sum(len(ln) for ln in stripped if ln in dup_values)
            char_frac = (dup_chars / total_chars) if total_chars else 0.0
            if line_frac > MAX_DUP_LINE_FRACTION and char_frac > MAX_DUP_CHAR_FRACTION:
                return "repetitive"

    return None


def code_quality_ok(text: str, path=None) -> bool:
    """True to KEEP a code file (see :func:`code_quality_reason`)."""
    return code_quality_reason(text, path) is None


# --------------------------------------------------------------------------- #
# Doc (markdown) quality
# --------------------------------------------------------------------------- #
def _is_license_line(stripped_lower: str) -> bool:
    return any(tok in stripped_lower for tok in _LICENSE_LINE_TOKENS)


def _doc_prose(text: str, drop_license: bool = False) -> str:
    """Visible prose with markup / links / badges / code fences removed.

    Markdown links become their display text (so inline-linked prose survives),
    while images/badges, bare URLs, HTML tags, and fenced/inline code are
    dropped entirely. When ``drop_license`` is set, lines that are license /
    copyright boilerplate are removed too (used by the license-only check).
    """
    s = text
    s = re.sub(r"<!--.*?-->", " ", s, flags=re.DOTALL)      # HTML comments
    s = re.sub(r"```.*?```", " ", s, flags=re.DOTALL)       # fenced code
    s = re.sub(r"~~~.*?~~~", " ", s, flags=re.DOTALL)       # fenced code (~)
    s = re.sub(r"`[^`]*`", " ", s)                          # inline code
    s = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", s)             # images / badges
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r" \1 ", s)        # links -> text
    s = re.sub(r"https?://\S+", " ", s)                     # bare URLs
    s = re.sub(r"<[^>]+>", " ", s)                          # HTML tags

    out: List[str] = []
    for line in s.splitlines():
        st = line.strip()
        if not st:
            continue
        if drop_license and _is_license_line(st.lower()):
            continue
        st = re.sub(r"^[#>\-\*\+\|=\s]+", "", st)           # leading md markers
        st = st.replace("|", " ")
        if st.strip():
            out.append(st.strip())
    prose = " ".join(out)
    prose = re.sub(r"[*_~>#`]", " ", prose)                 # residual markdown
    return prose


def doc_quality_reason(text: str, path=None) -> Optional[str]:
    """Return ``None`` to KEEP a markdown doc, else a short reason to DROP.

    Checks (in order):
      1. ``doc_too_short`` — raw stripped length < ``MIN_DOC_CHARS``.
      2. ``license_only`` — a license/SPDX marker is present and essentially no
         non-license prose remains (bare license/SPDX header stub).
      3. ``low_prose`` — after stripping markup/links/badges/code, too little
         prose remains (< ``MIN_DOC_PROSE_CHARS`` alpha chars or
         < ``MIN_DOC_WORDS`` words): nav-only / badge-only stubs.
    """
    if not text or not text.strip():
        return "doc_too_short"
    if len(text.strip()) < MIN_DOC_CHARS:
        return "doc_too_short"

    low = text.lower()
    if any(marker in low for marker in _LICENSE_MARKERS):
        prose_wo_license = _doc_prose(text, drop_license=True)
        if sum(1 for c in prose_wo_license if c.isalpha()) < MIN_DOC_PROSE_CHARS:
            return "license_only"

    prose = _doc_prose(text)
    prose_alpha = sum(1 for c in prose if c.isalpha())
    n_words = len(re.findall(r"[A-Za-z][A-Za-z0-9'\u2019]*", prose))
    if prose_alpha < MIN_DOC_PROSE_CHARS or n_words < MIN_DOC_WORDS:
        return "low_prose"

    return None


def doc_quality_ok(text: str, path=None) -> bool:
    """True to KEEP a markdown doc (see :func:`doc_quality_reason`)."""
    return doc_quality_reason(text, path) is None


# --------------------------------------------------------------------------- #
# Batch filter
# --------------------------------------------------------------------------- #
def quality_filter(
    files: Iterable[Tuple[object, str]],
    is_doc: bool = False,
) -> Tuple[List[Tuple[object, str]], dict]:
    """Filter ``(path, text)`` items through the code or doc gate.

    Args:
        files: iterable of ``(path, text)`` tuples (``path`` may be ``None``).
        is_doc: use :func:`doc_quality_reason` instead of
            :func:`code_quality_reason` (for markdown docs).

    Returns:
        ``(kept, stats)`` where ``kept`` preserves the input items that passed
        (in order) and ``stats`` is
        ``{"in": n, "kept": k, "dropped": d, "drop_reasons": {reason: count}}``.
    """
    reason_fn = doc_quality_reason if is_doc else code_quality_reason
    kept: List[Tuple[object, str]] = []
    drop_reasons: dict = {}
    n_in = 0
    for item in files:
        n_in += 1
        path, text = item[0], item[1]
        reason = reason_fn(text, path)
        if reason is None:
            kept.append(item)
        else:
            drop_reasons[reason] = drop_reasons.get(reason, 0) + 1
    stats = {
        "in": n_in,
        "kept": len(kept),
        "dropped": n_in - len(kept),
        "drop_reasons": drop_reasons,
    }
    return kept, stats


__all__ = [
    # thresholds
    "MAX_LINE_LENGTH", "MAX_MEAN_LINE_LENGTH", "MIN_ALNUM_FRACTION",
    "MIN_CODE_LINES", "MIN_CODE_CHARS", "MAX_DUP_LINE_FRACTION",
    "MAX_DUP_CHAR_FRACTION", "REPETITION_MIN_LINES", "GENERATED_HEAD_CHARS",
    "MIN_DOC_CHARS", "MIN_DOC_PROSE_CHARS", "MIN_DOC_WORDS",
    # reason vocabularies
    "CODE_DROP_REASONS", "DOC_DROP_REASONS",
    # predicates
    "code_quality_ok", "code_quality_reason",
    "doc_quality_ok", "doc_quality_reason",
    "quality_filter",
]
