#!/usr/bin/env python
"""Build the v5 replay mixture, budgeted in tokens rather than rows.

The replay we inherited looks like six balanced buckets and is not. Measured with
the target tokenizer:

    math_reasoning        5,998 rows   ~65M tokens   79% of general replay
    general_code          5,999 rows   ~5.7M
    general_chat          7,984 rows   ~2.9M
    instruction_following 3,111 rows   ~1.1M

By rows it reads as 42% replay. By tokens -- the unit every mixture result in the
literature is stated in, and the unit the optimizer actually sees -- it is about
17%, and four fifths of that is one bucket of 5,998 rows.

Worse, that bucket is long chain-of-thought distilled from a reasoning model, and
the target model's chat template contains no thinking block. It is a non-thinking
instruct model. So the largest single component of our forgetting insurance is
teaching the model to emit long reasoning monologues it was never built to
produce -- a deliberate, large move away from the base policy, when the whole
purpose of replay is to stay near it. Forgetting tracks the KL between the tuned
and base policy on the training distribution, which makes this bucket closer to
the cause of forgetting than the cure.

So: cut long-CoT math from ~65M to ~25M tokens, and spend what that frees on
short-form chat, general code, and tool use, which are the capabilities a kernel
specialist most plausibly loses. Row count roughly triples while the token share
barely moves, because breadth is bought in short rows.

Two rules that are easy to get wrong and expensive to discover late:

* **Tool-call syntax must be re-rendered.** Every public tool-use corpus encodes
  calls in its own JSON schema; this model emits a bespoke XML ``<tool_call>``
  block. Training on foreign syntax teaches the model to produce calls the
  inference stack cannot parse, which presents exactly like catastrophic
  forgetting and is entirely self-inflicted.
* **Replay needs decontaminating too.** Ours never has been. The general-code
  corpora plausibly contain Triton and CUDA content, so a benchmark screen over
  replay is the difference between measuring generalisation and measuring recall.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path("/home/shasriva/Kore-RL/KORE")
sys.path.insert(0, str(REPO))

MODEL_ID = "Qwen/Qwen3-Coder-30B-A3B-Instruct"
REVISION = "b2cff646eb4bb1d68355c01b18ae02e7cf42d120"
TOKEN_LIMIT = 16896

#: bucket -> (hf_id, config, split, target_rows, note)
#: Chosen for licence first, then measured tokens/row, then provenance. Sizes are
#: a token budget expressed as rows; the builder reports what it actually got.
SOURCES = [
    # Row counts are a TOKEN budget expressed as rows, using measured tokens/row:
    # ~571 for Dolci, ~976 Ling-Coder, ~957 OpenCodeInstruct, ~290 opc-stage2,
    # ~918 ToolACE. The aim is ~121M replay tokens, i.e. 25% of the total, which
    # the previous pass missed at 74M because the row counts were set by eye.
    ("chat",     "allenai/Dolci-Instruct-SFT",   None,                    "train", 60000),
    ("code",     "inclusionAI/Ling-Coder-SFT",   None,                    "train", 35000),
    ("code",     "nvidia/OpenCodeInstruct",      None,                    "train", 14000),
    ("code",     "OpenCoder-LLM/opc-sft-stage2", "educational_instruct",  "train", 10000),
    ("code",     "OpenCoder-LLM/opc-sft-stage2", "evol_instruct",         "train",  8000),
    ("tool_use", "Team-ACE/ToolACE",             None,                    "train", 11000),
    # Toucan's Qwen3 split is generated by this model's own family, which is the
    # closest thing to on-policy tool-use replay available off the shelf; an
    # earlier pass kept 0 of 12,000 because three schema quirks stack (see
    # kore.data.tooluse_normalize).
    ("tool_use", "Agent-Ark/Toucan-1.5M",        "Qwen3",                 "train", 10000),
    ("tool_use", "Agent-Ark/Toucan-1.5M",        "SFT",                   "train",  8000),
    ("tool_use", "NousResearch/hermes-function-calling-v1", "func_calling",   "train", 1800),
    ("tool_use", "NousResearch/hermes-function-calling-v1", "glaive_func_calling", "train", 4000),

]

_MSG_KEYS = ("messages", "conversations", "conversation", "chat")
_ROLE_MAP = {"human": "user", "gpt": "assistant", "system": "system",
             "user": "user", "assistant": "assistant", "tool": "tool",
             "function": "tool", "observation": "tool"}


def to_messages(row: dict) -> list | None:
    """Normalise a row from any of these corpora into role/content messages.

    Several corpora keep the system prompt in its own column rather than as the
    first message, and for tool-use sets that column is where the tool schema
    lives -- dropping it turns a grounded call into an unexplained one.
    """
    system = row.get("system")
    prefix = ([{"role": "system", "content": system}]
              if isinstance(system, str) and system.strip() else [])
    for k in _MSG_KEYS:
        v = row.get(k)
        if isinstance(v, list) and v:
            out = []
            for m in v:
                if not isinstance(m, dict):
                    return None
                role = str(m.get("role") or m.get("from") or "").lower()
                role = _ROLE_MAP.get(role, role)
                content = m.get("content") if "content" in m else m.get("value")
                if role not in ("system", "user", "assistant", "tool"):
                    return None
                calls = m.get("tool_calls")
                if not isinstance(content, str):
                    content = "" if calls else None
                if content is None or (not content.strip() and not calls):
                    return None
                msg = {"role": role, "content": content}
                if calls:
                    msg["tool_calls"] = calls
                out.append(msg)
            if not out:
                return None
            if prefix and out[0].get("role") != "system":
                out = prefix + out
            return out
    # Instruction/response pairs, the other common shape.
    for ik, ok in (("instruction", "output"), ("input", "output"),
                   ("prompt", "completion"), ("question", "response")):
        i, o = row.get(ik), row.get(ok)
        if isinstance(i, str) and isinstance(o, str) and i.strip() and o.strip():
            return prefix + [{"role": "user", "content": i},
                             {"role": "assistant", "content": o}]
    return None


def usable(msgs: list) -> bool:
    """Ends on an assistant turn, no empty content, no foreign call syntax in text.

    The ``tool`` role itself is fine -- the target template renders it natively,
    and rejecting it would throw away every row in a tool-use corpus, which is
    what an earlier version of this function did.

    What is not fine is a *foreign tool-call schema pasted into assistant text*.
    This model emits calls as an XML block; training it on some other corpus's
    JSON shape teaches it to produce calls the inference stack cannot parse, and
    that failure looks exactly like forgetting while being entirely self-inflicted.
    Structured ``tool_calls`` fields are kept and left to the template to render;
    text-embedded calls in a foreign shape are dropped, because rewriting them
    would mean inventing the argument mapping and a wrong call trained as a target
    is worse than one fewer row.
    """
    if not msgs or msgs[-1].get("role") != "assistant":
        return False
    for m in msgs:
        role = m.get("role")
        c = m.get("content") or ""
        if role == "assistant" and not c.strip() and not m.get("tool_calls"):
            return False
        if role != "assistant" and not c.strip():
            return False
        # Our own XML surface is what the normalisers produce, so it is allowed.
        # A FOREIGN schema is not: a JSON call body belongs to a different model.
        if role == "assistant" and re.search(
                r'"(?:tool_calls|function_call|tool_uses)"\s*:', c):
            return False
        if role == "assistant" and re.search(r"<\s*(?:function|functioncall)\s*=", c):
            return False
    return True


def strip_reasoning(text: str) -> str:
    """Remove chain-of-thought scaffolding aimed at a thinking model."""
    for pat in (r"<think>.*?</think>", r"<thinking>.*?</thinking>",
                r"<\|begin_of_thought\|>.*?<\|end_of_thought\|>",
                r"<reasoning>.*?</reasoning>"):
        text = re.sub(pat, "", text, flags=re.S | re.I)
    return text.strip()


def h(msgs: list) -> str:
    return hashlib.sha1(json.dumps(msgs, sort_keys=True).encode()).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "data/v5_replay.jsonl"))
    ap.add_argument("--existing", default=str(REPO / "data/b05factory/sft/multicap_v3.jsonl"))
    ap.add_argument("--math-token-budget", type=int, default=25_000_000)
    ap.add_argument("--limit", type=int, default=TOKEN_LIMIT)
    args = ap.parse_args()

    from kore.data.tooluse_normalize import NORMALIZERS
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(MODEL_ID, revision=REVISION)

    def ntok(msgs) -> int:
        try:
            return len(tok.apply_chat_template(msgs, tokenize=True,
                                               add_generation_prompt=False))
        except Exception:  # noqa: BLE001 - a row that will not render is unusable
            return 10 ** 9

    seen: set[str] = set()
    out_rows: list[dict] = []
    budget: collections.Counter = collections.Counter()
    stats: collections.Counter = collections.Counter()

    # Carry the existing general slices, minus long-CoT math which is capped, and
    # minus kernel_qa which is domain data misfiled as replay.
    print("=== existing replay ===", flush=True)
    math_tokens = 0
    with open(args.existing, errors="ignore") as fh:
        for line in fh:
            try:
                d = json.loads(line)
            except Exception:  # noqa: BLE001
                continue
            src = str(d.get("_source") or "")
            if src.startswith("kernel"):
                stats["skip_kernel_side"] += 1
                continue
            msgs = d.get("messages") or []
            if not msgs:
                continue
            msgs = [{**m, "content": strip_reasoning(m.get("content") or "")}
                    for m in msgs]
            if not usable(msgs):
                stats[f"unusable::{src}"] += 1
                continue
            n = ntok(msgs)
            if n > args.limit:
                stats[f"too_long::{src}"] += 1
                continue
            if src in ("math_reasoning", "math"):
                if math_tokens + n > args.math_token_budget:
                    stats["math_over_budget"] += 1
                    continue
                math_tokens += n
            k = h(msgs)
            if k in seen:
                stats["dup"] += 1
                continue
            seen.add(k)
            out_rows.append({"messages": msgs, "_source": src,
                             "_provenance": {"kind": "replay_v4"}, "_tokens": n})
            budget[src] += n
    print(f"  carried {len(out_rows):,} rows, {sum(budget.values()):,} tokens")
    print(f"  math capped at {math_tokens:,} tokens "
          f"(budget {args.math_token_budget:,})")
    for k, v in stats.most_common(8):
        print(f"    {k:<30} {v:,}")

    # New sources.
    try:
        from datasets import load_dataset
    except ImportError:
        print("datasets not installed; carried-only build", file=sys.stderr)
        load_dataset = None

    if load_dataset is not None:
        for bucket, hf_id, config, split, want in SOURCES:
            print(f"\n=== {bucket:<9} {hf_id} [{config or '-'}] (want {want:,}) ===",
                  flush=True)
            got = 0
            try:
                ds = load_dataset(hf_id, config, split=split, streaming=True)
                for row in ds:
                    if got >= want:
                        break
                    # Per-row isolation. A single malformed payload must cost one
                    # row, not the whole source: an unserialisable argument in one
                    # Toucan row previously aborted the loop at zero kept.
                    try:
                        msgs = (NORMALIZERS[hf_id](row) if hf_id in NORMALIZERS
                                else to_messages(row))
                    except Exception:  # noqa: BLE001 - one bad row is not the corpus
                        stats[f"rowerror::{hf_id}"] += 1
                        continue
                    if not msgs:
                        stats[f"noshape::{hf_id}"] += 1
                        continue
                    msgs = [{**m, "content": strip_reasoning(m.get("content") or "")}
                            for m in msgs]
                    if not usable(msgs):
                        stats[f"unusable::{hf_id}"] += 1
                        continue
                    n = ntok(msgs)
                    if n > args.limit:
                        stats[f"too_long::{hf_id}"] += 1
                        continue
                    k = h(msgs)
                    if k in seen:
                        stats["dup"] += 1
                        continue
                    seen.add(k)
                    out_rows.append({
                        "messages": msgs, "_source": f"replay_{bucket}",
                        "_provenance": {"kind": "replay", "hf": hf_id},
                        "_tokens": n})
                    budget[f"replay_{bucket}"] += n
                    got += 1
            except Exception as exc:  # noqa: BLE001 - one dead source is not fatal
                print(f"  FAILED: {type(exc).__name__}: {str(exc)[:200]}",
                      file=sys.stderr)
            print(f"  kept {got:,}")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as fh:
        for r in out_rows:
            fh.write(json.dumps(r) + "\n")

    total = sum(budget.values())
    print(f"\n=== v5 replay: {len(out_rows):,} rows, {total:,} tokens ===")
    for k, v in budget.most_common():
        n = sum(1 for r in out_rows if r["_source"] == k)
        print(f"  {k:<26} {n:>7,} rows  {v:>12,} tok  {100*v/max(1,total):5.1f}%")
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
