"""Repository-side Phase-0 sandbox boundary.

The default subprocess backend is explicitly ``trusted-code-only``. Strong
untrusted isolation requires the external broker contract documented here.
"""

from kore.sandbox.broker import (
    BrokerClientProtocol,
    PeerCredentialPolicy,
    PeerCredentials,
    UnixBrokerClient,
    encode_frame,
    peer_credentials,
    recv_frame,
    send_frame,
)
from kore.sandbox.canonical import (
    canonical_json_bytes,
    canonical_json_text,
    policy_digest,
    runtime_digest,
    source_digest,
    task_digest,
    toolchain_digest,
)
from kore.sandbox.config import SandboxConfig
from kore.sandbox.controller import (
    BrokerIsolationController,
    CleanupHook,
    IsolationController,
    TrustedSubprocessController,
    classify_execution,
    create_isolation_controller,
)
from kore.sandbox.environment import (
    CANDIDATE_ENV_ALLOWLIST,
    INHERITED_ENV_ALLOWLIST,
    assert_safe_candidate_environment,
    build_candidate_environment,
)
from kore.sandbox.errors import (
    BrokerUnavailable,
    DigestMismatch,
    FrameTooLarge,
    InvalidLaunchPlan,
    OutputTooLarge,
    PeerCredentialError,
    PolicyViolation,
    ReplayDetected,
    SandboxConfigurationError,
    SandboxError,
    SignatureVerificationError,
    SizeLimitExceeded,
    SourceTooLarge,
    UnsupportedIsolationMode,
    VerdictVerificationError,
)
from kore.sandbox.launch_plan import (
    ArgumentKind,
    BufferAccess,
    BufferSpec,
    GridSpec,
    HsacoImage,
    KernelLaunch,
    LaunchArgument,
    LaunchCaps,
    LaunchPlan,
    ScalarSpec,
    ScalarType,
)
from kore.sandbox.models import (
    DigestSet,
    ExecutionKind,
    ExecutionStatus,
    GpuHealthStatus,
    IsolationMode,
    IsolationPolicy,
    ResourceBudget,
    SandboxRequest,
    SandboxResponse,
    SandboxVerdict,
    SignedVerdict,
    TrustLevel,
    fresh_nonce,
)
from kore.sandbox.signing import (
    EphemeralLocalHMAC,
    NonceRegistry,
    VerdictSignatureVerifier,
    VerdictSigner,
    sign_verdict,
    verify_signed_verdict,
)

__all__ = [
    "ArgumentKind",
    "BrokerClientProtocol",
    "BrokerIsolationController",
    "BufferAccess",
    "BufferSpec",
    "BrokerUnavailable",
    "CANDIDATE_ENV_ALLOWLIST",
    "CleanupHook",
    "DigestSet",
    "DigestMismatch",
    "EphemeralLocalHMAC",
    "ExecutionKind",
    "ExecutionStatus",
    "FrameTooLarge",
    "GpuHealthStatus",
    "GridSpec",
    "HsacoImage",
    "INHERITED_ENV_ALLOWLIST",
    "IsolationController",
    "IsolationMode",
    "IsolationPolicy",
    "InvalidLaunchPlan",
    "KernelLaunch",
    "LaunchArgument",
    "LaunchCaps",
    "LaunchPlan",
    "NonceRegistry",
    "OutputTooLarge",
    "PeerCredentialPolicy",
    "PeerCredentials",
    "PeerCredentialError",
    "PolicyViolation",
    "ReplayDetected",
    "ResourceBudget",
    "SandboxConfig",
    "SandboxConfigurationError",
    "SandboxError",
    "SandboxRequest",
    "SandboxResponse",
    "SandboxVerdict",
    "ScalarSpec",
    "ScalarType",
    "SignedVerdict",
    "SignatureVerificationError",
    "SizeLimitExceeded",
    "SourceTooLarge",
    "TrustLevel",
    "TrustedSubprocessController",
    "UnixBrokerClient",
    "UnsupportedIsolationMode",
    "VerdictSignatureVerifier",
    "VerdictSigner",
    "VerdictVerificationError",
    "assert_safe_candidate_environment",
    "build_candidate_environment",
    "canonical_json_bytes",
    "canonical_json_text",
    "classify_execution",
    "create_isolation_controller",
    "encode_frame",
    "fresh_nonce",
    "peer_credentials",
    "policy_digest",
    "recv_frame",
    "runtime_digest",
    "send_frame",
    "sign_verdict",
    "source_digest",
    "task_digest",
    "toolchain_digest",
    "verify_signed_verdict",
]
